# Same as full workflow (eg from fortio/multicurl) but without the goreleaser step
name: "CI Checks"

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    call-gochecks:
        uses: fortio/workflows/.github/workflows/gochecks.yml@main
    call-codecov:
        uses: fortio/workflows/.github/workflows/codecov.yml@main
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    call-codeql:
        uses: fortio/workflows/.github/workflows/codeql-analysis.yml@main
